### ISSUE TITLE
No sound on Acer Chromebook Spin 11

### ISSUE THREAD

**Issue by QL100100** [cb-linux/breath#170]
Despite the new apl-sof-setup-audio script, my sound card still went undetected. 
Only "default"(which is Pulseaudio's dummy output) shows up in alsamixer.
![image](https://user-images.githubusercontent.com/96569117/164712252-1a5f6feb-d1ef-450a-a3dd-f072509f3e90.png)

**Comment by QL100100** [comment]
[dmesg.txt](https://github.com/cb-linux/breath/files/8545371/dmesg.txt
http://alsa-project.org/db/?f=cbcd17f9e743a3cc7031f723d28bbbb76857a2b1

**Comment by QL100100** [comment]
I also forgot to mention I run Debian

**Comment by QL100100** [comment]
Here's a dmesg output from the Chrome OS shell if it is to be of use:
[dmesg.txt](https://github.com/cb-linux/breath/files/8546991/dmesg.txt)

**Comment by QL100100** [comment]
I purged pulseaudio and blacklisted snd-soc-skl and snd-hda-intel(Heard that it makes the sof driver load instead).
It still doesn't work.

**Comment by MilkyDeveloper** [comment]
I don't know if `apl-sof-setup-audio` ran properly. Your device should be SOF supported. What's in the file `/etc/systemd/system/alsa-reload.service`?

**Comment by QL100100** [comment]
[Unit]
Description="Reload ALSA and set the correct UCM"

[Service]
User=root
WorkingDirectory=/
ExecStart=/bin/bash -c 'modprobe snd_soc_max98357a snd_soc_da7219 && alsa reload'

[Install]
WantedBy=multi-user.target

**Comment by MilkyDeveloper** [comment]
What about running `modprobe bxt_da7219_max98357a && alsa reload`? That would be a stopgap solution, though.

Preferably we should use SOF. Blacklisting those modules might not make SOF load. I think you should put `options snd-intel-dspcfg dsp_driver=3` in `/etc/modprobe.d/test.conf`, reboot, and show `dmesg`.

**Comment by MilkyDeveloper** [comment]
Nevermind, that's already in the kernel parameters.

**Comment by QL100100** [comment]
sudo modprobe snd-soc-sst-bxt-da7219_max98357a snd-soc-kbl_da7219_max98357a snd-sof-pci-intel-apl && alsa reload
bash: alsa: command not found

**Comment by QL100100** [comment]
The above happened.
I know this may seem like a dumb question, but I can't find an answer anywhere

**Comment by MilkyDeveloper** [comment]
Maybe run `systemctl restart alsa-state` instead of `alsa reload`?

**Comment by QL100100** [comment]
[dmesg.txt](https://github.com/cb-linux/breath/files/8610477/dmesg.txt)

**Comment by QL100100** [comment]
By the way, the sound still doesn't work
"cat /proc/asound/cards" returns with "--- no soundcards ---"

**Comment by MilkyDeveloper** [comment]
This is our error:
```
[  128.948429] snd_soc_sst_bxt_da7219_max98357a: unknown parameter 'snd-soc-kbl_da7219_max98357a' ignored
[  128.948440] snd_soc_sst_bxt_da7219_max98357a: unknown parameter 'snd-sof-pci-intel-apl' ignored
```

I've never encountered anything like this before.

**Comment by MilkyDeveloper** [comment]
I think an `lsmod` from ChromeOS would also be useful - once we get the correct modules loaded, this should be fixed and I'll add it to `apl-setup-audio`.

**Comment by QL100100** [comment]
[lsmod.txt](https://github.com/cb-linux/breath/files/8628824/lsmod.txt)
Here's the lsmod from Chrome OS shell

**Comment by QL100100** [comment]
> This is our error:
> 
> ```
> [  128.948429] snd_soc_sst_bxt_da7219_max98357a: unknown parameter 'snd-soc-kbl_da7219_max98357a' ignored
> [  128.948440] snd_soc_sst_bxt_da7219_max98357a: unknown parameter 'snd-sof-pci-intel-apl' ignored
> ```
> 
> I've never encountered anything like this before. What if you just modprobe `sudo modprobe snd_soc_max98357a snd_soc_da7219` and reload ALSA?

I tried your command.
Sadly, it's still "--- no soundcards ---"

**Comment by MilkyDeveloper** [comment]
`modprobe snd_soc_max98357a snd_soc_da7219 snd-sof-pci-intel-apl sof-pci-dev && sudo alsa reload`

**Comment by QL100100** [comment]
[dmesg.txt](https://github.com/cb-linux/breath/files/8638881/dmesg.txt)

**Comment by MilkyDeveloper** [comment]
Maybe blacklist `snd_hda_intel`?

**Comment by MilkyDeveloper** [comment]
```
[    5.959231] da7219 i2c-DLGS7219:00: Invalid micbias pulse level
[    6.290841] pci 0000:00:0e.0: attach allowed to drvr snd_hda_intel [internal device]
[    6.330036] iwlwifi 0000:01:00.0 wlp1s0: renamed from wlan0
[    6.838134] pci 0000:00:0e.0: attach allowed to drvr snd_soc_skl [internal device]
```
and the the thing just... stops for some reason.

Try rerunning the whole script `setup.sh` again (on the PC you built Breath with of course), but first remove `~/linux-build`. I've published a few changes that should allow you to enable dynamic debug (i'll explain this later).

**Comment by Theriatheblack** [comment]
I've got the same device, and got this error:
`fatal: destination path 'sof-bin' already exists and is not an empty directory.`

**Comment by MilkyDeveloper** [comment]
Alright, that error helps much more. Try running:
```
rm -rf ~/sof-bin
```

**Comment by Theriatheblack** [comment]
Sorry, I forgot to delete that comment. I just re-ran the script and the problem disappeard. 
Sound still isn't working.

**Comment by MilkyDeveloper** [comment]
What’s the output of `sudo dmesg`?

**Comment by Theriatheblack** [comment]
[dmesg.txt](https://github.com/cb-linux/breath/files/8926121/dmesg.txt)

**Comment by MilkyDeveloper** [comment]
Hmmm, what about `lsmod`? There’s a chance that manually loading the `da7219` module will help.

**Comment by Theriatheblack** [comment]
Here's lsmod
[lsmod.txt](https://github.com/cb-linux/breath/files/8938875/lsmod.txt)
How do you load da7219?

**Comment by Theriatheblack** [comment]
Here's the lsmod:
[lsmod.txt](https://github.com/cb-linux/breath/files/8938913/lsmod.txt)
How do you load the da7219 module?
I tried `sudo modprobe da7219` and it doesn't find it.
